services:
  redis:
    image: "redis:alpine"
    restart: always

  web:
    build:
      context: .
      args:
        - GITHUB_REPOSITORY
        - BASE_IMAGE_TAG
    ports:
      - "8000:5000"
    volumes:
      - generated_data:/app/generated
      - uploads_data:/app/uploads
    command: /opt/venv/bin/python -m gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 300 app:app
    depends_on:
      - redis
    restart: always

  worker:
    build:
      context: .
      args:
        - GITHUB_REPOSITORY
        - BASE_IMAGE_TAG
    command: /opt/venv/bin/python -m celery -A app.celery worker --loglevel=info
    volumes:
      - generated_data:/app/generated
      - uploads_data:/app/uploads
    depends_on:
      - redis
    restart: always

volumes:
  uploads_data:
  generated_data:
