name: Continuous Integration and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space on Runner
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        swift: true
        golang: true
        docker-images: false

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python Dependencies (including piper-tts)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup FFmpeg (Static Build)
      run: |
        mkdir -p ~/ffmpeg
        curl -sL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz | tar xJ --strip-components=1 -C ~/ffmpeg
        echo "$HOME/ffmpeg" >> $GITHUB_PATH

    - name: Set up Docker Buildx and install Compose
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker services
      run: docker compose build

    - name: Start the services in the background
      run: docker compose up -d

    - name: Wait for the web service to be healthy
      run: |
        echo "Waiting for web service..."
        timeout=60
        while ! curl --silent --fail http://localhost:8000/health; do
          timeout=$((timeout-5))
          if [ $timeout -le 0 ]; then
            echo "Service timed out."
            docker compose logs
            exit 1
          fi
          sleep 5
        done
        echo "Web service is up!"

    - name: Make test script executable
      run: chmod +x tests/run_tests.sh

    - name: Run tests
      run: ./tests/run_tests.sh
      
    - name: Stop services and show logs on failure
      if: always()
      run: |
        if [[ ${{ job.status }} == 'failure' ]]; then
          echo "Tests failed. Displaying container logs..."
          docker compose logs
        fi
        docker compose down

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
